app.info.environment=PRODUCTION
app.info.message=You are running in PROD mode
app.info.version=1.0-prod

spring.datasource.url=jdbc:postgresql://localhost:5001/db
spring.datasource.username=admin_user
spring.datasource.password=password