app.info.environment=DEVELOPMENT
app.info.message=You are running in DEVs mode
app.info.version=1.0-prod

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://patient-service-db:5432/db
spring.datasource.username=admin_user
spring.datasource.password={cipher}381ce1c54349d213f039db15ecfc697ed37b1b48440845516e858631aa610c13
